---
development:
  cloud_name: hsfd0xshp
  api_key: '832374119173976'
  api_secret: bx4cHGU7WppufjMFEZzY4_JKpjY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hsfd0xshp
  api_key: '832374119173976'
  api_secret: bx4cHGU7WppufjMFEZzY4_JKpjY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hsfd0xshp
  api_key: '832374119173976'
  api_secret: bx4cHGU7WppufjMFEZzY4_JKpjY
  enhance_image_tag: true
  static_file_support: false
